name: CI

on:
  push:
    branches:
    - develop

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: npm install
    - run: npm build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
